version: '3.8'

services:
  minecraft-server:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    environment:
      EULA: "TRUE" # Accept the Minecraft EULA
      MEMORY: "8G" # Set the memory allocation
    volumes:
      - ./data:/data # Persist server data
    restart: unless-stopped

  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    ports:
      - "19999:19999"
    volumes:
      - netdata:/etc/netdata
      - netdata-lib:/var/lib/netdata
      - netdata-cache:/var/cache/netdata
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped

  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    ports:
      - "8080:8080" # Admin interface
      - "8443:8443" # Admin interface (SSL)
      - "8081:80"   # HTTP traffic
      - "8444:443"  # HTTPS traffic
      - "25565:25565" # Minecraft server traffic
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  netdata:
  netdata-lib:
  netdata-cache:
  portainer-data: